-- Create groups table
CREATE TABLE public.groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  description text NULL,
  CONSTRAINT groups_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create device table
CREATE TABLE public.device (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  serial text NULL,
  client_id bigint NULL,
  friendly_name text NULL,
  device_model text NULL,
  status text NULL,
  group_id bigint NULL,
  CONSTRAINT device_pkey PRIMARY KEY (id),
  CONSTRAINT device_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.groups(id) ON DELETE SET NULL
) TABLESPACE pg_default;

-- Enable Row Level Security on groups table
ALTER TABLE public.groups ENABLE ROW LEVEL SECURITY;

-- Enable Row Level Security on device table
ALTER TABLE public.device ENABLE ROW LEVEL SECURITY;

-- Create policies for groups table
-- Policy: Allow all users to view groups
CREATE POLICY "Allow public read access to groups"
  ON public.groups
  FOR SELECT
  USING (true);

-- Policy: Allow authenticated users to insert groups
CREATE POLICY "Allow authenticated users to insert groups"
  ON public.groups
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Policy: Allow authenticated users to update groups
CREATE POLICY "Allow authenticated users to update groups"
  ON public.groups
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Policy: Allow authenticated users to delete groups
CREATE POLICY "Allow authenticated users to delete groups"
  ON public.groups
  FOR DELETE
  TO authenticated
  USING (true);

-- Create policies for device table
-- Policy: Allow all users to view devices
CREATE POLICY "Allow public read access to devices"
  ON public.device
  FOR SELECT
  USING (true);

-- Policy: Allow authenticated users to insert devices
CREATE POLICY "Allow authenticated users to insert devices"
  ON public.device
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Policy: Allow authenticated users to update devices
CREATE POLICY "Allow authenticated users to update devices"
  ON public.device
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Policy: Allow authenticated users to delete devices
CREATE POLICY "Allow authenticated users to delete devices"
  ON public.device
  FOR DELETE
  TO authenticated
  USING (true);

-- Create indexes for better performance
CREATE INDEX device_group_id_idx ON public.device(group_id);
CREATE INDEX device_status_idx ON public.device(status);
CREATE INDEX device_serial_idx ON public.device(serial);

