-- Create mvr_device_groups table
CREATE TABLE public.mvr_device_groups (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  description text NULL,
  CONSTRAINT mvr_device_groups_pkey PRIMARY KEY (id)
) TABLESPACE pg_default;

-- Create mvr_devices table
CREATE TABLE public.mvr_devices (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  serial text NULL,
  client_id bigint NULL,
  friendly_name text NULL,
  device_model text NULL,
  status text NULL,
  group_id bigint NULL,
  CONSTRAINT mvr_devices_pkey PRIMARY KEY (id),
  CONSTRAINT mvr_devices_group_id_fkey FOREIGN KEY (group_id) REFERENCES public.mvr_device_groups(id) ON DELETE SET NULL
) TABLESPACE pg_default;

-- Enable Row Level Security on mvr_device_groups table
ALTER TABLE public.mvr_device_groups ENABLE ROW LEVEL SECURITY;

-- Enable Row Level Security on mvr_devices table
ALTER TABLE public.mvr_devices ENABLE ROW LEVEL SECURITY;

-- Create policies for mvr_device_groups table
-- Policy: Allow all users to view groups
CREATE POLICY "Allow public read access to groups"
  ON public.mvr_device_groups
  FOR SELECT
  USING (true);

-- Policy: Allow authenticated users to insert groups
CREATE POLICY "Allow authenticated users to insert groups"
  ON public.mvr_device_groups
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Policy: Allow authenticated users to update groups
CREATE POLICY "Allow authenticated users to update groups"
  ON public.mvr_device_groups
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Policy: Allow authenticated users to delete groups
CREATE POLICY "Allow authenticated users to delete groups"
  ON public.mvr_device_groups
  FOR DELETE
  TO authenticated
  USING (true);

-- Create policies for mvr_devices table
-- Policy: Allow all users to view devices
CREATE POLICY "Allow public read access to devices"
  ON public.mvr_devices
  FOR SELECT
  USING (true);

-- Policy: Allow authenticated users to insert devices
CREATE POLICY "Allow authenticated users to insert devices"
  ON public.mvr_devices
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

-- Policy: Allow authenticated users to update devices
CREATE POLICY "Allow authenticated users to update devices"
  ON public.mvr_devices
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- Policy: Allow authenticated users to delete devices
CREATE POLICY "Allow authenticated users to delete devices"
  ON public.mvr_devices
  FOR DELETE
  TO authenticated
  USING (true);

-- Create indexes for better performance
CREATE INDEX mvr_devices_group_id_idx ON public.mvr_devices(group_id);
CREATE INDEX mvr_devices_status_idx ON public.mvr_devices(status);
CREATE INDEX mvr_devices_serial_idx ON public.mvr_devices(serial);

